#!/usr/bin/python

import argparse
import os
import io
import zipfile
import xml.dom
import barcode

###########################
# Define Token Parameters #
###########################
PAGE_WIDTH = 290  # mm
PAGE_HEIGHT = 210  # mm
TOKEN_SPACING = 2  # mm
TOKEN_WIDTH = 55  # mm
TOKEN_HEIGHT = 25  # mm
BORDER_RADIUS = 3  # mm
BARCODE_X_OFFSET = 5  # mm
BARCODE_Y_OFFSET = 6  # mm
BARCODE_LINE_WIDTH = 0.4  # mm
BARCODE_LINE_HEIGHT = 10  # mm
HOLE_X_OFFSET = 7  # mm
HOLE_DIA = 4  # mm
TEXT_Y_OFFSET = 5  # mm
FOREGROUND_COLOUR = "#000000"
BACKGROUND_COLOUR = "#ffffff"
FONT_SIZE = 12

# Resolution for PNG/JPG output (300 dpi = good print quality)
OUTPUT_DPI = 300

SIZE = "{0:.3f}mm"


def _set_attributes(element, **attributes):
    for key, value in attributes.items():
        element.setAttribute(key, value)


def create_svg_object(with_doctype=False):
    imp = xml.dom.getDOMImplementation()
    doctype = imp.createDocumentType(
        "svg",
        "-//W3C//DTD SVG 1.1//EN",
        "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd",
    )
    document = imp.createDocument(None, "svg", doctype if with_doctype else None)
    _set_attributes(
        document.documentElement, version="1.1", xmlns="http://www.w3.org/2000/svg"
    )
    return document


def makeToken(tokenVal, titleStr="Parkrun Finish Token"):
    document = create_svg_object(False)
    root = document.documentElement
    barcode.writer._set_attributes(root,
        width=SIZE.format(TOKEN_WIDTH),
        height=SIZE.format(TOKEN_HEIGHT))
    root.appendChild(document.createComment("Generated by finish_tokens.py"))

    groupElem = document.createElement("g")
    barcode.writer._set_attributes(groupElem, id="token_group")
    group = root.appendChild(groupElem)

    background = document.createElement("rect")
    barcode.writer._set_attributes(background,
        width="100%", height="100%",
        style="fill:%s" % BACKGROUND_COLOUR)
    group.appendChild(background)

    tokenBorder = document.createElement("rect")
    barcode.writer._set_attributes(tokenBorder,
        width=SIZE.format(TOKEN_WIDTH),
        height=SIZE.format(TOKEN_HEIGHT),
        rx=SIZE.format(BORDER_RADIUS),
        ry=SIZE.format(BORDER_RADIUS),
        style="fill:transparent; stroke:black; stroke-width:3;")
    group.appendChild(tokenBorder)

    tokenHole = document.createElement("circle")
    barcode.writer._set_attributes(tokenHole,
        cx=SIZE.format(TOKEN_WIDTH - HOLE_X_OFFSET),
        cy=SIZE.format(TOKEN_HEIGHT / 2.),
        r=SIZE.format(HOLE_DIA / 2.),
        style="fill:transparent; stroke:black; stroke-width:3;")
    group.appendChild(tokenHole)

    element = document.createElement("text")
    barcode.writer._set_attributes(element,
        x=SIZE.format(TOKEN_WIDTH / 2.),
        y=SIZE.format(TEXT_Y_OFFSET),
        style="fill:{};font-size:{}pt;text-anchor:middle;".format(FOREGROUND_COLOUR, FONT_SIZE))
    element.appendChild(document.createTextNode(titleStr))
    group.appendChild(element)

    elem = document.createElement("svg")
    barcode.writer._set_attributes(elem,
        x=SIZE.format(BARCODE_X_OFFSET),
        y=SIZE.format(BARCODE_Y_OFFSET))
    tokenCode = barcode.Code128(tokenVal)
    tokenCode.render(writer_options={"with_doctype": False,
                                     "module_width": BARCODE_LINE_WIDTH,
                                     "module_height": BARCODE_LINE_HEIGHT})
    elem.appendChild(tokenCode.writer._root)
    group.appendChild(elem)

    return(root)


def makeTokensPage(tokensList, titleStr="tokenPage"):
    document = create_svg_object(True)
    root = document.documentElement
    barcode.writer._set_attributes(root,
        width=SIZE.format(PAGE_WIDTH),
        height=SIZE.format(PAGE_HEIGHT))
    root.appendChild(document.createComment("Generated by finish_tokens.py"))

    xpos = TOKEN_SPACING
    ypos = TOKEN_SPACING
    for tokenVal in tokensList:
        print("making token: %s" % tokenVal)
        elem = document.createElement("svg")
        barcode.writer._set_attributes(elem,
            x=SIZE.format(xpos),
            y=SIZE.format(ypos))
        elem.appendChild(makeToken(tokenVal, titleStr=titleStr))
        root.appendChild(elem)

        xpos = xpos + TOKEN_WIDTH + TOKEN_SPACING
        if (xpos > PAGE_WIDTH - TOKEN_WIDTH - TOKEN_SPACING):
            xpos = TOKEN_SPACING
            ypos = ypos + TOKEN_HEIGHT + TOKEN_SPACING
        if (ypos > PAGE_HEIGHT - TOKEN_HEIGHT - TOKEN_SPACING):
            print("end of page")
            break

    svgTxt = document.toprettyxml(indent=4 * " ", newl=os.linesep, encoding="UTF-8")
    return(svgTxt)


def svg_to_png_bytes(svgTxt):
    """Convert SVG bytes to PNG bytes using cairosvg."""
    import cairosvg
    return cairosvg.svg2png(bytestring=svgTxt, dpi=OUTPUT_DPI)


def svg_to_jpg_bytes(svgTxt):
    """Convert SVG bytes to JPG bytes via cairosvg + Pillow."""
    from PIL import Image
    png_bytes = svg_to_png_bytes(svgTxt)
    img = Image.open(io.BytesIO(png_bytes)).convert("RGBA")
    white_bg = Image.new("RGBA", img.size, (255, 255, 255, 255))
    white_bg.paste(img, mask=img.split()[3])  # use alpha channel as mask
    jpg_buf = io.BytesIO()
    white_bg.convert("RGB").save(jpg_buf, format="JPEG", quality=95)
    return jpg_buf.getvalue()

def write_page(svgTxt, outFileStem, pageNo, fmt):
    """Write a single page to disk in the requested format."""
    fmt = fmt.lower()
    if fmt == "svg":
        outPath = "%s_%d.svg" % (outFileStem, pageNo)
        with open(outPath, "w") as f:
            f.write(svgTxt.decode("utf-8"))
    elif fmt == "png":
        outPath = "%s_%d.png" % (outFileStem, pageNo)
        with open(outPath, "wb") as f:
            f.write(svg_to_png_bytes(svgTxt))
    elif fmt in ("jpg", "jpeg"):
        outPath = "%s_%d.jpg" % (outFileStem, pageNo)
        with open(outPath, "wb") as f:
            f.write(svg_to_jpg_bytes(svgTxt))
    else:
        raise ValueError("Unsupported format: %s (choose svg, png, or jpg)" % fmt)
    print("Written: %s" % outPath)


def makeTokenList(tokenListStr):
    tokenLst = []
    if isinstance(tokenListStr, list):
        tokenListStr = ' '.join(tokenListStr)
    tokenListStrSpaceSep = tokenListStr.replace(',', ' ')
    for tokId in tokenListStrSpaceSep.split(' '):
        print(tokId)
        if tokId.isdigit():
            tokenLst.append("P%04d" % int(tokId))
        else:
            if (len(tokId.split('-')) == 2):
                startStr, endStr = tokId.split('-')
                for n in range(int(startStr), int(endStr) + 1):
                    tokenLst.append("P%04d" % n)
    return(tokenLst)


def getTokensPerPage():
    nrows = int((PAGE_HEIGHT - TOKEN_SPACING) / (TOKEN_HEIGHT + TOKEN_SPACING))
    ncols = int((PAGE_WIDTH - TOKEN_SPACING) / (TOKEN_WIDTH + TOKEN_SPACING))
    tokensPerPage = nrows * ncols
    print("getTokensPerPage(): nrows=%d, ncols=%d, tokens per page = %d" %
          (nrows, ncols, tokensPerPage))
    return(tokensPerPage)


def getTokensZipFile(tokenLst, titleStr, fmt="svg"):
    """Returns a BytesIO zip containing all pages in the requested format."""
    fmt = fmt.lower()
    ext = "jpg" if fmt in ("jpg", "jpeg") else fmt
    tokensPerPage = getTokensPerPage()

    startToken = 0
    pageNo = 1
    outFilesLst = []
    while(startToken < len(tokenLst)):
        pageTokens = tokenLst[startToken:startToken + tokensPerPage]
        svgTxt = makeTokensPage(pageTokens, titleStr=titleStr)

        if fmt == "svg":
            fileContents = svgTxt
        elif fmt == "png":
            fileContents = svg_to_png_bytes(svgTxt)
        elif fmt in ("jpg", "jpeg"):
            fileContents = svg_to_jpg_bytes(svgTxt)

        outFilesLst.append(("tokens_%d.%s" % (pageNo, ext), fileContents))
        pageNo += 1
        startToken = (pageNo - 1) * tokensPerPage

    mem_zip = io.BytesIO()
    with zipfile.ZipFile(mem_zip, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
        for f in outFilesLst:
            zf.writestr(f[0], f[1])
    mem_zip.seek(0)
    return(mem_zip)


def main():
    print("finish_tokens.main()")

    parser = argparse.ArgumentParser()
    parser.add_argument("tokenListInput", nargs="+",
                        help="list of token numbers and ranges (e.g. 3 4 10-15 21-23 30)")
    parser.add_argument("-f", "--outFile", default="tokenPage",
                        help="output filename without extension (default: 'tokenPage')")
    parser.add_argument("-t", "--title", default="Parkrun Finish Token",
                        help="title printed on each token")
    parser.add_argument("--format", default="svg", choices=["svg", "png", "jpg"],
                        help="output format: svg (default), png, or jpg")
    args = vars(parser.parse_args())
    print(args)

    # Check dependencies up front before doing any work
    if args['format'] in ("png", "jpg"):
        try:
            import cairosvg
        except ImportError:
            print("ERROR: cairosvg is required for PNG/JPG output.")
            print("Install with:  pip install cairosvg")
            return
    if args['format'] == "jpg":
        try:
            from PIL import Image
        except ImportError:
            print("ERROR: Pillow is required for JPG output.")
            print("Install with:  pip install Pillow")
            return

    tokenLst = makeTokenList(args['tokenListInput'])
    tokensPerPage = getTokensPerPage()

    startToken = 0
    pageNo = 1
    while(startToken < len(tokenLst)):
        pageTokens = tokenLst[startToken:startToken + tokensPerPage]
        startToken += tokensPerPage
        svgTxt = makeTokensPage(pageTokens, titleStr=args['title'])
        write_page(svgTxt, args['outFile'], pageNo, args['format'])
        pageNo += 1
        startToken = (pageNo - 1) * tokensPerPage


if (__name__ == "__main__"):
    main()
